<?php

use Illuminate\Foundation\Application;

// Minimal bootstrap placeholder — real bootstrap will be generated by
// `composer create-project laravel/laravel` when the project is initialised.
return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__ . '/../routes/web.php',
        api: __DIR__ . '/../routes/api.php',
        commands: __DIR__ . '/../routes/console.php',
    )
    ->withMiddleware(function ($middleware) {})
    ->withExceptions(function ($exceptions) {})
    ->create();
