<?php

// Front controller — real content generated by `composer create-project laravel/laravel`.
// Placeholder only for scaffold step.
define('LARAVEL_START', microtime(true));

require __DIR__ . '/../vendor/autoload.php';

$app = require_once __DIR__ . '/../bootstrap/app.php';

$app->handleRequest(Illuminate\Http\Request::capture());
