#!/usr/bin/env php
<?php

/**
 * Laravel artisan entry point.
 * Real bootstrap wires in after `composer create-project laravel/laravel .`
 * is run over this scaffold.
 */

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new Symfony\Component\Console\Input\ArgvInput);

exit($status);
